// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgHitFRCLNuJlLifVz_4J_DfjheBHGYj4',
    appId: '1:912875835453:web:edfec42f76f1cd162e1a54',
    messagingSenderId: '912875835453',
    projectId: 'lokafood-003',
    authDomain: 'lokafood-003.firebaseapp.com',
    storageBucket: 'lokafood-003.firebasestorage.app',
    measurementId: 'G-X3FXZNG3GQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTEY-fauJosddfxAfpF-_m7IrcNNTZVWo',
    appId: '1:912875835453:android:5c41758f8f2476b72e1a54',
    messagingSenderId: '912875835453',
    projectId: 'lokafood-003',
    storageBucket: 'lokafood-003.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDarcCXRmnmBhDljmeRBaocs3ZfJ1kJcsI',
    appId: '1:912875835453:ios:3c70cf7f5f75c3502e1a54',
    messagingSenderId: '912875835453',
    projectId: 'lokafood-003',
    storageBucket: 'lokafood-003.firebasestorage.app',
    iosBundleId: 'com.example.lokafood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDarcCXRmnmBhDljmeRBaocs3ZfJ1kJcsI',
    appId: '1:912875835453:ios:3c70cf7f5f75c3502e1a54',
    messagingSenderId: '912875835453',
    projectId: 'lokafood-003',
    storageBucket: 'lokafood-003.firebasestorage.app',
    iosBundleId: 'com.example.lokafood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgHitFRCLNuJlLifVz_4J_DfjheBHGYj4',
    appId: '1:912875835453:web:6260cbbb04af9bff2e1a54',
    messagingSenderId: '912875835453',
    projectId: 'lokafood-003',
    authDomain: 'lokafood-003.firebaseapp.com',
    storageBucket: 'lokafood-003.firebasestorage.app',
    measurementId: 'G-VG7BV32W29',
  );
}
